// Artifact vocabulary for WD-40: what a target is, which group it belongs to,
// and how a size reads. Discovery lives in `discover`, measurement in `sizes`.
// Exports: `TargetDir`, `ArtifactKind`, `ArtifactGroup`, `human_size`,
// `sizes_may_overlap`. Deps: std only.

use std::path::PathBuf;
use std::time::SystemTime;

/// True when any target lives under a shared cargo target root. `aid` seeds
/// those per-session dirs with `cp -Rc` (APFS clone), so their reported sizes
/// share physical blocks and summing them overstates what a delete returns.
/// See docs/apfs-clone-overcount.md.
pub fn sizes_may_overlap(paths: &[PathBuf]) -> bool {
    paths.iter().any(|path| {
        path.components()
            .any(|component| component.as_os_str() == ".cargo-target")
    })
}

#[derive(Clone)]
pub struct TargetDir {
    pub path: PathBuf,
    pub size_bytes: u64,
    pub last_modified: SystemTime,
    pub kind: ArtifactKind,
}

#[derive(Clone, Copy)]
pub enum ArtifactKind {
    RustTarget,
    NodeModules,
    BuildOutput,
    Cache,
    Toolchain,
    TmpTarget,
}

impl ArtifactKind {
    /// What a directory name discovered by the walk stands for. `discover` and
    /// the settings screen have to agree on this, or a group could be switched
    /// off and still be found.
    pub fn for_dir_name(name: &str) -> Self {
        match name {
            "target" => Self::RustTarget,
            "node_modules" => Self::NodeModules,
            _ => Self::BuildOutput,
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::RustTarget => "target",
            Self::NodeModules => "node_modules",
            Self::BuildOutput => "build",
            Self::Cache => "cache",
            Self::Toolchain => "toolchain",
            Self::TmpTarget => "tmp-target",
        }
    }

    pub fn group(self) -> ArtifactGroup {
        match self {
            Self::RustTarget | Self::TmpTarget => ArtifactGroup::Rust,
            Self::NodeModules => ArtifactGroup::NodeModules,
            Self::BuildOutput => ArtifactGroup::BuildOutput,
            Self::Cache => ArtifactGroup::Caches,
            Self::Toolchain => ArtifactGroup::Toolchains,
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum ArtifactGroup {
    Rust,
    NodeModules,
    BuildOutput,
    Caches,
    Toolchains,
}

/// What each group scans for, shown in its info panel.
const RUST_HELP: &str = "\
Scans for Rust compilation artifacts:

\u{2022} target/ \u{2014} Cargo build output
  Detected by: contains debug/ or release/ subdirectory

\u{2022} /tmp/*-target, /tmp/*-target-*, /tmp/cc-target-* \u{2014}
  Temporary Cargo build dirs (Claude Code & ad-hoc CARGO_TARGET_DIR)

\u{2022} ~/.cargo-target/*/ \u{2014} Per-project dirs under shared CARGO_TARGET_DIR root

\u{2022} ~/.aid/worktrees/<repo>/<branch>/target \u{2014}
  Cargo targets inside aid-managed git worktrees
\u{2022} .claude/worktrees/ and .worktrees/ \u{2014} nested project targets

Safe to delete \u{2014} regenerated by `cargo build`.";

const NODE_HELP: &str = "\
Scans for Node.js dependency directories:

\u{2022} node_modules/ \u{2014} npm/yarn installed packages
  Detected by: parent package.json or package manager files inside the directory

Safe to delete \u{2014} regenerated by `npm install` or `yarn install`.";

const BUILD_HELP: &str = "\
Scans for build tool output directories:

\u{2022} .next/ \u{2014} Next.js build cache
  Detected by: contains cache/ or static/ subdirectory

\u{2022} dist/, build/ \u{2014} Project build output
  Detected by: project manifest, Xcode project, or build/CMakeCache.txt
\u{2022} .build/ \u{2014} SwiftPM output (parent Package.swift)
\u{2022} .gradle/ \u{2014} Gradle project state (parent Gradle build/settings file)
\u{2022} .turbo/, .svelte-kit/, .parcel-cache/, .nuxt/ \u{2014} Node builds (parent package.json)
\u{2022} .angular/ \u{2014} Angular output (parent angular.json)
\u{2022} .mypy_cache/, .pytest_cache/, .ruff_cache/ \u{2014} Python tool caches (cache tag or tool files)
\u{2022} .tox/, .nox/ \u{2014} Python test environments (parent tox.ini, noxfile.py or pyproject.toml)
\u{2022} zig-cache/, .zig-cache/, zig-out/ \u{2014} Zig output (parent build.zig)
\u{2022} .dart_tool/ \u{2014} Dart output (parent pubspec.yaml)
\u{2022} out/ \u{2014} Foundry output (parent foundry.toml)
\u{2022} artifacts/ \u{2014} Hardhat output (parent hardhat.config.js/ts/cjs/mjs)

Safe to delete \u{2014} regenerated by running the build command.";

const TOOLCHAIN_HELP: &str = "\
Scans for installed Rust toolchains:

\u{2022} ~/.rustup/toolchains/<channel>-<host> \u{2014} one row per toolchain

Never offered: the default toolchain, anything `rustup override` points at,
and any channel a rust-toolchain.toml under your scan roots pins. Toolchains
added with `rustup toolchain link` are left alone \u{2014} they point at a build
tree of your own.

Removed with `rustup toolchain uninstall`, never by deleting the directory,
so rustup's record of what is installed stays true. Reinstalling one is a
network download, not a rebuild.";

const CACHE_HELP: &str = "\
Scans for regenerable developer caches:

\u{2022} DerivedData/ \u{2014} Xcode build cache
\u{2022} ModuleCache.noindex/ \u{2014} Xcode module cache
\u{2022} ~/Library/Caches/org.swift.swiftpm/ \u{2014} SwiftPM package cache
\u{2022} ~/Library/Caches/com.apple.dt.Xcode/ \u{2014} Xcode cache
\u{2022} ~/Library/Developer/Xcode/* DeviceSupport/ \u{2014} Xcode platform support
\u{2022} CoreSimulator/Devices/*/data/Library/Caches/ \u{2014} simulator caches
\u{2022} ~/.cargo/registry \u{2014} crate downloads, sources and index
\u{2022} ~/.npm/_cacache, pnpm and Yarn stores
\u{2022} Homebrew cache dirs
\u{2022} ~/Library/Caches/pip/ \u{2014} pip cache
\u{2022} ~/.cache/uv/, ~/Library/Caches/uv/ \u{2014} uv caches
\u{2022} ~/Library/Caches/go-build/ \u{2014} Go build cache (not module cache)
\u{2022} ~/.gradle/caches/ \u{2014} Gradle cache
\u{2022} ~/.gradle/wrapper/dists/ \u{2014} Gradle distributions
\u{2022} ~/.bun/install/cache/ \u{2014} Bun cache
\u{2022} ~/Library/Caches/CocoaPods/ \u{2014} CocoaPods cache
\u{2022} ~/Library/Caches/node-gyp/ \u{2014} node-gyp cache
\u{2022} ~/Library/Caches/Mozilla.sccache/ \u{2014} sccache
\u{2022} ~/Library/Caches/deno/ \u{2014} Deno cache
\u{2022} ~/.npm/_npx/ \u{2014} npx cache
\u{2022} ~/Library/Developer/CoreSimulator/Caches/ \u{2014} simulator cache

Safe to delete \u{2014} rebuilds may need network downloads.";

impl ArtifactGroup {
    pub const ALL: &[ArtifactGroup] = &[
        ArtifactGroup::Rust,
        ArtifactGroup::NodeModules,
        ArtifactGroup::BuildOutput,
        ArtifactGroup::Caches,
        ArtifactGroup::Toolchains,
    ];

    pub fn label(self) -> &'static str {
        match self {
            Self::Rust => "Rust",
            Self::NodeModules => "Node Modules",
            Self::BuildOutput => "Build Output",
            Self::Caches => "Caches",
            Self::Toolchains => "Toolchains",
        }
    }

    /// How the group is named to the user in the popover.
    pub fn title(self) -> &'static str {
        match self {
            Self::Rust => "Rust targets",
            Self::NodeModules => "node_modules",
            Self::BuildOutput => "Build output",
            Self::Caches => "Caches",
            Self::Toolchains => "Rust toolchains",
        }
    }

    /// Stable key for the config file. Never derived from `label`, which is
    /// prose and may be reworded.
    pub fn key(self) -> &'static str {
        match self {
            Self::Rust => "rust",
            Self::NodeModules => "node_modules",
            Self::BuildOutput => "build_output",
            Self::Caches => "caches",
            Self::Toolchains => "toolchains",
        }
    }

    /// SF Symbol shown next to the group header.
    pub fn symbol(self) -> &'static str {
        match self {
            Self::Rust => "gearshape.2",
            Self::NodeModules => "shippingbox",
            Self::BuildOutput => "hammer",
            // externaldrive.badge.clock does not exist on every macOS the app runs on,
            // and a missing symbol draws nothing at all.
            Self::Caches => "clock.arrow.circlepath",
            Self::Toolchains => "wrench.and.screwdriver",
        }
    }

    pub fn tag(self) -> isize {
        match self {
            Self::Rust => 0,
            Self::NodeModules => 1,
            Self::BuildOutput => 2,
            Self::Caches => 3,
            Self::Toolchains => 4,
        }
    }

    pub fn from_tag(tag: isize) -> Option<Self> {
        match tag {
            0 => Some(Self::Rust),
            1 => Some(Self::NodeModules),
            2 => Some(Self::BuildOutput),
            3 => Some(Self::Caches),
            4 => Some(Self::Toolchains),
            _ => None,
        }
    }

    pub fn description(self) -> &'static str {
        match self {
            Self::Rust => RUST_HELP,
            Self::NodeModules => NODE_HELP,
            Self::BuildOutput => BUILD_HELP,
            Self::Caches => CACHE_HELP,
            Self::Toolchains => TOOLCHAIN_HELP,
        }
    }
}

pub fn human_size(bytes: u64) -> String {
    let mut value = bytes as f64;
    let mut unit = 0;
    let units = ["B", "K", "M", "G", "T"];
    while value >= 1024.0 && unit < units.len() - 1 {
        value /= 1024.0;
        unit += 1;
    }
    if unit == 0 {
        format!("{}{}", bytes, units[unit])
    } else {
        format!("{:.1}{}", value, units[unit])
    }
}

#[cfg(test)]
mod tests {
    use super::sizes_may_overlap;
    use std::path::PathBuf;

    #[test]
    fn shared_cargo_root_targets_can_overlap() {
        let paths = vec![PathBuf::from("/Users/x/.cargo-target/proj/session-a")];
        assert!(sizes_may_overlap(&paths));
    }

    #[test]
    fn ordinary_project_targets_do_not_overlap() {
        let paths = vec![
            PathBuf::from("/Users/x/Develop/proj/target"),
            PathBuf::from("/Users/x/Develop/web/node_modules"),
        ];
        assert!(!sizes_may_overlap(&paths));
    }
}
